/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "こんにちは";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        // System.out.println(System.getProperty("file.encoding"));

        // MySQL に接続
        String PROPATIES = "?characterEncoding=UTF-8&serverTimezone=JST";
        String url = "jdbc:mysql://localhost:3306/mysql";

        String user = "root";
        String password = "mysql";
        // Connection con = DriverManager.getConnection(url, user, password);
        try {
            //MySQL に接続する
            Class.forName("com.mysql.cj.jdbc.Driver");
            //データベースに接続
            Connection conn = DriverManager.getConnection(url, user, password);

            // データベースに対する処理
            System.out.println("データベースに接続に成功");

        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }

    }
}
