CREATE TABLE daily_quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  code VARCHAR(10) NOT NULL,
  open NUMERIC(12,2),
  high NUMERIC(12,2),
  low NUMERIC(12,2),
  close NUMERIC(12,2),
  upper_limit NUMERIC(12,2),
  lower_limit NUMERIC(12,2),
  volume NUMERIC(20,0),
  turnover_value NUMERIC(20,2),
  adjustment_factor NUMERIC(10,4),
  adjustment_open NUMERIC(12,2),
  adjustment_high NUMERIC(12,2),
  adjustment_low NUMERIC(12,2),
  adjustment_close NUMERIC(12,2),
  adjustment_volume NUMERIC(20,0),

  CONSTRAINT uq_daily_quotes UNIQUE (date, code)
  CONSTRAINT fk_daily_quotes_company
    FOREIGN KEY (code)
    REFERENCES company(code)
    ON DELETE NO ACTION;
);