/*
 * This source file was generated by the Gradle 'init' task
 */
package org.stofli;

import java.io.IOException;
import java.time.LocalDate;

import org.stofli.adapter.database.repository.DailyQuoteRepositoryImpl;
import org.stofli.adapter.database.repository.TseDataRepositoryImpl;
import org.stofli.adapter.webapi.auth.JQuantsTokenProvider;
import org.stofli.adapter.webapi.auth.PropertiesCredentialProvider;
import org.stofli.adapter.webapi.auth.core.TokenProvider;
import org.stofli.adapter.webapi.jquants.JQuantsClient;
import org.stofli.application.service.DailyQuoteApplicationService;
import org.stofli.domain.port.MarketDataClient;
import org.stofli.domain.repository.DailyQuoteRepository;
import org.stofli.domain.repository.TseDataRepository;


public class App {

    public static void main(String[] args) throws IOException, InterruptedException {
        try {

            TseDataRepository tseDataRepository = new TseDataRepositoryImpl();
            DailyQuoteRepository dailyQuoteRepository = new DailyQuoteRepositoryImpl(); // new JdbcDailyQuoteRepository(DbUtil.getConnection());
            // TseDataImportService service = new TseDataImportService(tseDataRepository);
            // int count = service.importFrom(new ExcelFilePath("data_j.xls"));
            // System.out.println("Imported rows: " + count);



            PropertiesCredentialProvider credentialProvider = new PropertiesCredentialProvider();
            TokenProvider tokenProvider = new JQuantsTokenProvider(credentialProvider);
            MarketDataClient marketDataClient = new JQuantsClient(tokenProvider);
            DailyQuoteApplicationService dqService = new DailyQuoteApplicationService(tseDataRepository, dailyQuoteRepository, marketDataClient);
            LocalDate date = LocalDate.of(2024, 3, 6);
            dqService.importAllCompany(date);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
