/*
 * This source file was generated by the Gradle 'init' task
 */
package org.stofli;

import java.io.IOException;

import org.stofli.application.service.TseDataImportService;
import org.stofli.domain.model.ExcelFilePath;
import org.stofli.infrastructure.repository.TseDataRepositoryImpl;


public class App {

    public static void main(String[] args) throws IOException, InterruptedException {

        TseDataRepositoryImpl repo = new TseDataRepositoryImpl();
        TseDataImportService service = new TseDataImportService(repo);
        int count = service.importFrom(new ExcelFilePath("data_j.xls"));
        System.out.println("Imported rows: " + count);
        // Properties properties = PropertiesUtil.loadProperties("JQuants.properties");

        // ApiClient jquantClient = new ApiClient(properties.getProperty("mailAdress"), properties.getProperty("password"));
        // Optional<QuoteResponse> qr = jquantClient.getDailyQuates("9432", "20240306");
        
        // Optional<DailyQuote> qr = jquantClient.getDailyQuates("1332", "20240306");


     // private static void imoprtTseCompnayFromExcelData() {
        // Dotenv dotenv = Dotenv.load(); // .envを読み込む
        //
        // String host = dotenv.get("NEON_HOST");
        // String port = dotenv.get("NEON_PORT");
        // String db = dotenv.get("NEON_DB");
        // String user = dotenv.get("NEON_USER");
        // String pass = dotenv.get("NEON_PASSWORD");
        // String uri = dotenv.get("NEON_URI");
        // Excel excelDataBook = new TseExcel("data_j.xls");
        
        //
        // List<TseData> dataList = excelDataBook.readData();
        //
        // // String url = "jdbc:mysql://localhost:3306/stock";
        // // uri = uri.replace("postgresql://","jdbc:postgresql://");
        // String url = "jdbc:postgresql://" + host + ":5432/" + db + "?sslmode=require";
        //
        // try {
        //
        // // Class.forName("com.mysql.cj.jdbc.Driver");
        // Class.forName("org.postgresql.Driver");
        //
        // Connection conn = DriverManager.getConnection(url, user, pass);
        // StockCompanyDao scDao = new StockCompanyDao(conn);
        // scDao.insert(dataList);
        //
        // } catch (SQLException | ClassNotFoundException e) {
        // e.printStackTrace();
        // }
    }
}
